M48
; DRILL file {KiCad 9.0.7} date 2026-02-25T14:22:46+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-25T14:22:46+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X66.04Y-60.96
X66.04Y-119.38
X157.48Y-60.96
X157.48Y-119.38
M30
